#!/bin/bash

cache="$HOME/.cache/via/via_cache"
recent="$HOME/.cache/via/via_recent"

if [[ "$1" == "-r" ]] || [[ ! -e "$cache" ]]; then
    cat "$HOME/.config/via/shortcuts" > "$cache"
    cat "$HOME/.config/via/websites" >> "$cache"
    find "$HOME/Downloads" -maxdepth 1 -type f -name "*.pdf" >> $cache
    find "$HOME/Books" -maxdepth 1 -type f -name "*.pdf" >> $cache
    find "$HOME/gitclone" -maxdepth 2 -type f -name "config.def.h" >> $cache
    find "$HOME/gitclone" -maxdepth 1 -type d >> $cache
    find "$HOME/Projects" -maxdepth 1 -type d >> $cache
    find "$HOME/scripts" -maxdepth 1 -type f ! -name "*.sh" >> $cache
    echo "$HOME/.config/via" >> $cache
    printf "%s\n" "Telegram" \
        "firefox" \
        "obsidian" \
        "okular" \
        "zoom" \
        "pavucontrol" \
        "nautilus" \
        "scrot -s" \
        "$HOME/Qt/Tools/QtCreator/bin/qtcreator.sh" \
        "minecraft-launcher" \
        "code" \
        "vmware-view" \
        "virt-manager" >> $cache

fi

# sh -c "$HOME/scripts/dmenu_path" >> $cache

cat "$cache" "$recent" | sort | uniq -c | sort -rh | sed 's/\s*//' | cut -d' ' -f2-
